### ISSUE TITLE
Notification close button icon is broken

### ISSUE THREAD

**Issue by zhaolinlau** [oruga-ui/theme-bulma#103]
Overview of the problem

Oruga version: [0.8.7]
Vuejs version: [3.4.21]
OS/Browser: Windows 11, Firefox

### Description

close button not showing properly

```vue
<ONotification v-if="contactSuccess" :message="contactSuccess" iconSize="medium" variant="success" closable
			aria-close-label="Close notification" />
```

### Steps to reproduce

1. add `closable` to <ONotification  />
2. the `close` icon will look weird

### Expected behavior

![image](https://github.com/oruga-ui/theme-bulma/assets/68846168/34082081-d7b4-4f41-b505-9ada970ea967)

### Actual behavior

![image](https://github.com/oruga-ui/theme-bulma/assets/68846168/1bd89f59-a2bd-40e3-9016-7ed68ddd5710)

**Comment by andrzejkupczyk** [comment]
Hello @zhaolinlau , are you using the latest `theme-bulma` version?

https://github.com/oruga-ui/theme-bulma/issues/80#issuecomment-1969640932
