### ISSUE TITLE
Build fails with 0.4.1

### ISSUE THREAD

**Issue by mat813** [oruga-ui/theme-bulma#130]
After #124 being fixed, the build now fails with:

```
$ tsc       
node_modules/@oruga-ui/theme-bulma/dist/types/bulma.d.ts:1:35 - error TS2307: Cannot find module '@oruga-ui/oruga-next' or its corresponding type declarations.

1 import type { OrugaOptions } from "@oruga-ui/oruga-next";
                                    ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@oruga-ui/theme-bulma/dist/types/bulma.d.ts:1
```

But `@oruga-ui/oruga-next` is not defined as even a peer dependency. If I add it as a dev dep, it then fails because it can't find `vue` and `vue-component-type-helpers`, and if I add those two as dev deps, it finally builds.

My code is pretty simple, it's a generic module that I use to "patch" the config for all my projects:

```typescript
import { bulmaConfig as originalBulmaConfig } from '@oruga-ui/theme-bulma';
import { merge } from 'lodash';

export const bulmaConfig = merge(
  originalBulmaConfig,

  {
    iconPack: 'fa',
    iconComponent: 'FontAwesomeIcon',
    field: {
      fieldInputWrapperClass: 'field-body',
    },
  },
);
```

I am unsure what is the correct fix for that use case.

**Comment by mlmoravek** [comment]
Hey, thanks for the feedback! 

Maybe we should add `@oruga-ui/oruga-next` as a peerDependency, like Oruga has `vue` as peerDependency?

Also, that `vue-component-type-helpers` is required, is a problem with the current Oruga version and documented here: https://github.com/oruga-ui/oruga/issues/1038
