### ISSUE TITLE
Size property of Timepicker not working on theme-bulma 0.4.1

### ISSUE THREAD

**Issue by pflirae** [oruga-ui/theme-bulma#132]
### Overview of the problem

**Oruga** version: 0.9.0-pre.2
**Vuejs** version: 3.5.4
**OS/Browser**: not dependent of browser

### Description

No matter the value of the size property used with Timepicker, the component has a constant size

### Steps to reproduce

With this code and changing the size property, the problem can be reproduced:

```
<OField label="Hora muestra" class="column is-2 marginless no-bottom-padding">
      <OTimepicker v-model="hora_muestra" size="small" inline @mousedown.native="capturaClick" />
</OField>
```
On screen it looks this way:

![image](https://github.com/user-attachments/assets/26097d9d-0ec9-4aa3-a6ba-91b6c9aff8c5)

### Expected behavior

That the Timepicker component changes its size depending of the size prop value

### Actual behavior

Timepicker dos not change size if you change the sise prop value

**Comment by mlmoravek** [comment]
Was this possible before? I think this more an issue of the main package. The size prop only applies to the input field, not to the select elements of the dropdown.

**Comment by pflirae** [comment]
Yes it was possible before, with version oruga 0.8.12 and theme-bulma 0.3 it worked fine.

**Comment by pflirae** [comment]
Here is an image of the size working on previous version:

![image](https://github.com/user-attachments/assets/aef48be5-1712-4ebc-af24-b6cc3391acec)
