### ISSUE TITLE
Difficulty with '@use' to set colors

### ISSUE THREAD

**Issue by irees** [oruga-ui/theme-bulma#140]
Hi,

I've been using Bulma/Oruga successfully for several years. Thank you for maintaining this project.

I'm going through the process of upgrading to bulma 1.0.2 / oruga 0.9 / theme-bulma 0.4.3, and I cannot seem to get the `@use` to set custom colors. Currently, on a pre-1.0 bulma, I set the color variables and then import bulma the old fashioned way.

I have added a minimal nuxt app example here: https://github.com/interline-io/oruga-bulma-test which sets up an `oruga.ts` plugin, a `main.scss` file, and a simple example layout and test page. This setup is essentially how I have been using bulma / oruga in my other projects.

In `main.scss`, I have three configuration options, none of which quite works.

Styles both Bulma and Oruga components but no way to set colors:
```
@use '@oruga-ui/theme-bulma/dist/bulma.css';
```
<img width="1324" alt="Screenshot 2024-10-09 at 6 41 18 PM" src="https://github.com/user-attachments/assets/0f95f688-c697-4756-a861-94e7cdb9f37c">

Works with Bulma but Oruga components are not styled:
```
$primary: #ff0000;
@use 'bulma/sass' with (
     $primary: $primary,
);
```
<img width="1324" alt="Screenshot 2024-10-09 at 6 39 09 PM" src="https://github.com/user-attachments/assets/54c95703-1dfe-4071-b536-e21bfcb9d3f3">

Does not seem to work at all:
```
@use '@oruga-ui/theme-bulma/dist/scss/bulma' with (
    $primary: $primary,
);
```
<img width="1324" alt="Screenshot 2024-10-09 at 6 40 17 PM" src="https://github.com/user-attachments/assets/7321aa3d-88c6-4504-87d7-125ab80122fb">

Any advice on workarounds or possible solutions is welcome. Unfortunately, I'm not familiar enough with modern SCSS to debug and solve the issue with a PR myself.

**Comment by mlmoravek** [comment]
Hey, thanks for the feedback! 
I am also not that deep into the `@use' scss structure. If I did something wrong or missed something, feel free to make a PR!

I will check it, when I have time though :)

**Comment by drakeba** [comment]
Just wanted to echo this, thanks for reporting it @irees. I also am not super versed in the new scss syntax, but I'll be tinkering in it as well and will be watching this ticket in case you guys figure it out prior.

**Comment by drakeba** [comment]
I was able to get mine working with a minor work-around for now. First, I used the `bulma-build.scss` file instead of `bulma.scss`.

I'm also wondering if there's an issue with the Vite compiler? Because if I do this:

```
@use '@oruga-ui/theme-bulma/dist/scss/bulma-build' with (
    $primary: $primary,
);
```

...I get a Vite compilation error, but if I compile it using just SASS like this:

```
sass --watch --load-path=node_modules assets/scss/bulma-overrides.scss assets/scss/dist/output.css
```

... then it compiles as expected. Unless I've missed something, this suggest a minor documentation update in this library, but the issue is maybe in Vite itself?

**Comment by mlmoravek** [comment]
Hey, thanks everyone. I will update the readme. 
Here are working examples:



Using the following sample code you **don't need** `import '@oruga-ui/theme-bulma/dist/bulma.css'` but you have to add a custom sass/scss file to customize Bulma and the theme variables. 
To overwrite Bulma’s Sass variables with your own values, you have to use `@use` and the `with` keyword, which takes a Sass map.
You have two options for including the theme: include all the styling at once (including full bulma), or include the Oruga theme and Bulma separately.

```scss
// Option A: Include all styling (including bulma)

// set your color overrides
$primary: #8c67ef;
$link: $primary;

// add new colors to the colors map
$twitter: #4099FF;
$custom-colors: ('twitter': $twitter);

// Include the Oruga Bulma theme with Bulma included (you can only manipulate any derived variables here)
@use '@oruga-ui/theme-bulma/dist/scss/bulma-build' with (
    $family-primary: '"Nunito", sans-serif',
    $primary: $primary,
    $link: $link,
    $custom-colors: $custom-colors,
);

// Then add additional custom code here
// ...
```
**_NOTE:_** Note that only variables within Bulma's [derived-variables.scss](https://github.com/jgthms/bulma/blob/main/sass/utilities/derived-variables.scss) file can be overridden here.

```scss
// Option B: Include the Oruga theme and Bulma separately

// set your color overrides
$primary: #8c67ef;
$link: $primary;

// add new colors to the colors map
$twitter: #4099FF;
$custom-colors: ('twitter': $twitter);

// 1. Include the Oruga theme first (you can only manipulate any derived variables here)
@use '@oruga-ui/theme-bulma/dist/scss/bulma' with (
    $family-primary: '"Nunito", sans-serif',
    $primary: $primary,
    $link: $link,
    $custom-colors: $custom-colors,
);

// 2. Include any other Bulma module with specific configuration here
@use "bulma/sass/elements" with (
    $button-weight: 800
);

// 3. Include the remaining parts or full Bulma
@use "bulma/sass";

// Then add additional custom code here
// ...
```
