### ISSUE TITLE
Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by Norel** [oruga-ui/theme-bulma#32]
Using Nuxt 3 and building my project gives this warning for several component scss :

`Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.`

`Recommendation: math.div($switch-width, 2)`

Found in :

- dist/scss/components/_switch.scss 32:23
- dist/scss/components/_switch.scss 50:26
- dist/scss/components/_switch.scss 51:27
- dist/scss/components/utils/_functions.scss 17:18
- dist/scss/components/_slider.scss 20:17

It was apparently fixed in Bulma since 0.9.3 :
https://github.com/jgthms/bulma/issues/3364#issuecomment-864742234

**Comment by jtommy** [comment]
@Norel Just release 0.1.2

**Comment by Norel** [comment]
Working perfectly. Thanks a lot !
