### ISSUE TITLE
Tabs animation - slide issue

### ISSUE THREAD

**Issue by kadlinobit** [oruga-ui/theme-bulma#36]
Tabs slide animation seems broken - when switching tab, the old content slides out, but the new content doesn't slide in.

Example:
https://codesandbox.io/s/oruga-theme-bulma-tabs-issue-y1pbn

**Comment by jtommy** [comment]
You are right, there is a breaking change about transition on Vue 3.
We need to duplicate the scss animation code in order to work with both versions.

**Comment by kadlinobit** [comment]
> You are right, there is a breaking change about transition on Vue 3. We need to duplicate the scss animation code in order to work with both versions.

OK, sorry I forgot to mention it - but this is happening in Vue 2.
