### ISSUE TITLE
Missing declaration file

### ISSUE THREAD

**Issue by busheezy** [oruga-ui/theme-bulma#44]
The types are currently not exposed to the NPM package. This makes my environment angry.

Thanks

**Comment by jtommy** [comment]
Ok I'll add a quick fix but you can fix easily in your environment adding a "fake" types

**Comment by busheezy** [comment]
Thanks a bunch. I would love to have real types. Right now I am just using ``// @ts-ignore``.

**Comment by jtommy** [comment]
The package doesn't provide types but I can add it only to avoid you to add ignore

**Comment by jtommy** [comment]
https://github.com/oruga-ui/theme-bulma/commit/ae5960317231c24280ccc73b2260efc05ea8cdb6

**Comment by busheezy** [comment]
Thanks for the quick fix. I wanted to play with rollup to see if TS could do the type and ended up with this.

https://github.com/busheezy/theme-bulma/commit/d8582b702acb325198d506290c30944408089aa2

The result is the same so no real point for a PR.

Thanks again.
