### ISSUE TITLE
o-table pagination issue

### ISSUE THREAD

**Issue by kevinlogan94** [oruga-ui/theme-bulma#45]
Hey guys, I'm currently trying to integrate Oruga into my app that has been using Buefy. 

I'm using Oruga `0.5.2`  and theme-bulma `0.2.1`. 

I'm having an issue with the appearance of the pagination section when I use the Oruga Table Component `o-table`. 

When I compare it to Buefy's pagination for `b-table`, I notice that all the level classes aren't being applied. For example: `level top`, `level-right`, `level-left` and so on. 

As a temporary fix, I manually wrote the scss for the level classes to be applied to the pagination divs. 

I've included the styles below...

I think a more permanent solution will have to be an update to both theme-bulma and oruga. Oruga needs to have the customizations for those divs so theme-bulma can set the configuration for the level classes. Right now, the only customization for this is `paginationWrapperClass`, and theme-bulma sets this to empty when it should at least make it the `level` class.

```
// Temp solution to getting the pagination to look right.
.b-table.table-wrapper {
  margin-bottom: 0;

  .pagination-link {
    padding-left: 0.5em;
    padding-right: 0.5em;
  }

  + div {
    padding: 1.125rem 1.5rem;
    margin: 0;
    border-top: rgba(24, 28, 33, 0.06);
    background: #f5f5f5;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between;

    div {
      display: flex;
      flex-basis: auto;
      -webkit-box-flex: 0;
      flex-grow: 0;
      flex-shrink: 0;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
    }
    div:nth-child(1) {
      -webkit-box-pack: start;
      -ms-flex-pack: start;
      justify-content: flex-start;
    }
    div:nth-child(2) {
      -webkit-box-pack: end;
      -ms-flex-pack: end;
      justify-content: flex-end;

      div {
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        flex-basis: auto;
        -webkit-box-flex: 0;
        flex-grow: 0;
        flex-shrink: 0;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
      }
    }
  }
}
```

**Comment by jtommy** [comment]
@MaTTze any news about it?

**Comment by MaTTze** [comment]
@kevinlogan94 Can you take a look at #47? Does it fix your problem or did I miss something?

**Comment by kevinlogan94** [comment]
Yeah, that should handle the bulk of it. If you want to go ahead and push it out, I'm happy to test it on my end.
