### ISSUE TITLE
Switch disabled style is not applied

### ISSUE THREAD

**Issue by nioc** [oruga-ui/theme-bulma#50]
Hello,

I do not know if it is a theme-bulma or oruga issue but a switch with disabled property set is not render as expected (with `cursor: not-allowed;` and `color: #7a7a7a;`

Following example:
```html
<o-switch v-model="status" disabled />
```

Render like this:
```html
<label class="switch is-rounded">
  <input type="checkbox" class="" disabled="" true-value="true" false-value="false" value="false">
  <span class="check">
    ::before
    <span class=""></span>
  </span>
  <span class="control-label">
  </span>
</label>
```

Previously with buefy (0.9.10) / bulma (0.9.3):
``` html
<label disabled="disabled" class="switch is-disabled is-rounded">
  <input type="checkbox" disabled="disabled" true-value="true" value="false">
  <span class="check">
    ::before
  </span>
  <!---->
</label>
```

It seems `disabled="disabled"` is missing in `label` tag. After adding manually in DOM it works as expected.

oruga-next: "0.5.4"
theme-bulma: "0.2.2",
vue: "3.2.31",

**Comment by jtommy** [comment]
Yes, just apply a class to https://github.com/oruga-ui/theme-bulma/blob/74375ae3896b4b06e60599d538b0eb0c0320af4a/src/assets/scss/components/_switch.scss#L209 and bind it to config
