### ISSUE TITLE
Upload component shows extra, standard HTML "Choose File" button

### ISSUE THREAD

**Issue by Thaurin** [oruga-ui/theme-bulma#51]
Vue version: 3.2.25
Bulma theme: 0.2.2
Oruga: 0.5.4

Using the example of the base Upload component in the Oruga documentation, I'm getting two buttons: one o-button, and one that seems to be the standard upload element's button reading "Choose File".

I haven't looked into it yet, but has this component been confirmed working before with the Bulma plugin? Can't use it like this. :)

**Comment by jtommy** [comment]
You are right, just received the same issue on Discord

**Comment by Thaurin** [comment]
Great, that means I'm not going crazy. :) For now, this seems to work:

    input[type=file] {
      display: none;
    }

**Comment by Thaurin** [comment]
I celebrated too early. Upload component seems broken? The input event seem to not emit when a file is chosen.

**Comment by jtommy** [comment]
Check Buefy, it doesn't add display none.
Btw we'll fix it as soon as possible

**Comment by jtommy** [comment]
@Thaurin 0.2.3
