### ISSUE TITLE
Cannot load externally because of unexpected characters in global namespace

### ISSUE THREAD

**Issue by ztefn** [oruga-ui/theme-bulma#52]
Hello,

I like to load theme-bulma externally using webpack. But because the global name **@orugaUi/themeBulma** used in [bulma.js](https://cdn.jsdelivr.net/npm/@oruga-ui/theme-bulma@0.2.2/dist/bulma.js) contains non-ascii characters this is not possible. Works fine if I modify the bulma.js file myself to use a global name such as **themeBulma**.

Is there any chance the global name will be changed to something compatible with webpack in the near future? Or do you see this as a bug in webpack itself?

vue.config.js
```
  module.exports.configureWebpack = {
    externals: {
      "@oruga-ui/oruga-next": 'Oruga',
      "@oruga-ui/theme-bulma": "@orugaUi/themeBulma"
    }
  }
```

npm run build
```
Unexpected character '@' (1:35)
| var __WEBPACK_NAMESPACE_OBJECT__ = @orugaUi/themeBulma;
while analyzing module external var "@orugaUi/themeBulma" for concatenation

 ERROR  Error: Build failed with errors.
```

**Comment by jtommy** [comment]
There are other lib that are using @, what do you with them?

**Comment by ztefn** [comment]
> There are other lib that are using @, what do you with them?

While some libs use @ in their npm package name (for the organzation part) I haven't encountered any that use this as their global name. As you can see in my externals excerpt, Oruga itself uses **Oruga** as global, not _@oruga-ui/oruga-next_. FormKit uses **FormKitVue** not _@formkit/vue_. I think that's exactly for this reason.

**Comment by jtommy** [comment]
I'm sorry but I don't understand the difference between Oruga and FormKit. Both use @ in the package name

**Comment by ztefn** [comment]
With _global name_ I am referring to the global Javascript variable name when the library is used standalone. This is not the same as _package name_.

ForKit used FormKitVue as global name declared on line 1 of [formkit-vue.js](https://cdn.jsdelivr.net/npm/@formkit/vue@1.0.0-beta.5/dist/formkit-vue.js):
```
var FormKitVue = (function (exports, vue) {
```

Oruga UI uses Oruga as global name declared on line 5 of [oruga.js](https://cdn.jsdelivr.net/npm/@oruga-ui/oruga-next@0.5.4/dist/oruga.js):
```
    (global = global || self, factory(global.Oruga = {}, global.Vue));
```

theme-bulma sets the problematic "@orugaUi/themeBulma" as global name declared on line 4 of [bulma.js](https://cdn.jsdelivr.net/npm/@oruga-ui/theme-bulma@0.2.2/dist/bulma.js):
```
    (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global["@orugaUi/themeBulma"] = {}));
```

**Comment by jtommy** [comment]
Ahhh ok, now i understand i thought about a problem on Oruga too

**Comment by jtommy** [comment]
Yes! You can change it making a PR 😉
