### ISSUE TITLE
Datepicker header fields are not attached

### ISSUE THREAD

**Issue by nioc** [oruga-ui/theme-bulma#54]
Hello,

I have an issue with the datepicker component: month and year fields are not attached.

Following HTML rendered (differences seems to be `<div class="pagination-list">` children) and screenshots

With **Buefy (0.9.10) / bulma (0.9.3)**, I got this:

![image](https://user-images.githubusercontent.com/5225411/158284656-ce542c54-c80d-4841-b9b8-c058350e2637.png)

``` html
      <div class="field">
        <!---->
        <div class="field-body">
          <div class="field has-addons">
            <!---->
            <div class="control">
              <span class="select"><select>
                  <!---->
                  <option value="0"> January </option>
                  ...

            <div class="control">
              <span class="select">
                <select>
                  <!---->
                  <option value="2022"> 2022 </option>
```

And now with **oruga-next: (0.5.4) / theme-bulma (0.2.3)**, it display like this:

![image](https://user-images.githubusercontent.com/5225411/158284617-a15ee49c-b846-481d-97f0-1520154c1144.png)

``` html
    <div class="pagination-list">
      <div class="control select">
        <select class="">
          <!--v-if-->
          <option value="0">January</option>
          ...

      <div class="control select">
        <select class="">
          <!--v-if-->
          <option value="2022">2022</option>
```

I presume we need to have this missing part:

``` html
<div class="field">
  <div class="field-body">
    <div class="field has-addons">
```

I tried to add the [Bulma](https://bulma.io/documentation/form/general/#form-addons) `field has-addons` classes to the `div.pagination-list` using the `listsClass` prop but it overflows 😞:

![image](https://user-images.githubusercontent.com/5225411/158285794-389fab51-0a7e-4de5-a8bb-9fca4fe114b8.png)

Last (ugly) try, I updated the `.dropdown-menu` with `min-width: 25rem` ...

**Comment by nioc** [comment]
Update:

I cloned the `theme-bulma` repo, `datepicker` is ok.
In my application, I have a custom scss file in which I import the following:

```scss
@charset "utf-8";

@import "/node_modules/bulma/sass/utilities/initial-variables";
// also tryed @import "/node_modules/bulma/sass/utilities/_all";
// do some values tuning (color, ...)

@import "/node_modules/bulma/bulma.sass";
// do some component style tuning (colors, ...)

@import "/node_modules/@oruga-ui/theme-bulma/dist/scss/bulma";
// custom styles
```

I think I forget to import something... I'll give a try tonight.

**Comment by jtommy** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/8029488/158381022-f6cae628-c3cc-4073-bf85-47325749d5aa.png">

Month select is not attached to year but it looks ok

**Comment by jtommy** [comment]
> Update:
> 
> I cloned the `theme-bulma` repo, `datepicker` is ok. In my application, I have a custom scss file in which I import the following:
> 
> ```css-scss
> @charset "utf-8";
> 
> @import "/node_modules/bulma/sass/utilities/initial-variables";
> // also tryed @import "/node_modules/bulma/sass/utilities/_all";
> // do some values tuning (color, ...)
> 
> @import "/node_modules/bulma/bulma.sass";
> // do some component style tuning (colors, ...)
> 
> @import "/node_modules/@oruga-ui/theme-bulma/dist/scss/bulma";
> // custom styles
> ```
> 
> I think I forget to import something... I'll give a try tonight.

https://github.com/oruga-ui/theme-bulma#customization-sassscss, did you try following it?

**Comment by nioc** [comment]
For information, I found the conceptual difference with buefy datepicker: with oruga/theme-bulma it needs to be in a component with enough horizontal space. This can be shown in the demo page, if you apply a width <400px to the `div.column`, design breaks:

![image](https://user-images.githubusercontent.com/5225411/158393582-e47cc840-cd63-4c59-8016-dc5a233ecf0a.png)

In my existing application, datepicker was along others fields (inside a `div class="field is-grouped is-grouped-multiline is-block-mobile"`):

![image](https://user-images.githubusercontent.com/5225411/158392684-1d47f983-4072-4fa8-b178-4c375630fb84.png)

So i have to found a way for handle parent datepicker spacing without the need of have large field.
Do you have an idea for that?

**Comment by jtommy** [comment]
> For information, I found the conceptual difference with buefy datepicker: with oruga/theme-bulma it needs to be in a component with enough horizontal space. This can be shown in the demo page, if you apply a `max-width: 400px` to the `div.column`, design breaks:
> 
> ![image](https://user-images.githubusercontent.com/5225411/158393582-e47cc840-cd63-4c59-8016-dc5a233ecf0a.png)
> 
> In my existing application, datepicker was along others fields (inside a `div class="field is-grouped is-grouped-multiline is-block-mobile"`):
> 
> ![image](https://user-images.githubusercontent.com/5225411/158392684-1d47f983-4072-4fa8-b178-4c375630fb84.png)
> 
> So i have to found a way for handle parent datepicker spacing without the need of have large field. Do you have an idea for that?

Thanks to reproduce it. I'll take a look

**Comment by nioc** [comment]
I have found a dirty workaround:

- add prop `lists-class="field has-addons"` in template
- override css:
  ```css
  .datepicker .pagination-list {
    flex-wrap: nowrap; /* fix the horizontal spacing */
    .select {
      margin-left: 0; /* enhance field has-addons style */
      margin-right: 0;
    }
  }
  ```
