### ISSUE TITLE
sticky-header on table does not work with theme-bulma

### ISSUE THREAD

**Issue by urkle** [oruga-ui/theme-bulma#63]
adding the sticky-header prop on an o-table when using theme-bulma does nothing as

1) the configuration does not set a class for stickyHeaderClass
2) when using "has-sticky-header" it some-what works 
    - the first TR in the thead sticks
    - sticky columns, however, do not work

Other usability-questions regarding sticky Headers.
1) how does one get the filter row to also be sticky?
2) how does one control the height of the table when in "sticky" mode.  It seems odd to fix it at 300px always. (on a per-table basis not globally)

**Comment by jtommy** [comment]
I'll take a look at columns.

About height you can override using the scss variable https://github.com/oruga-ui/theme-bulma/blob/278541a5466af4b75c1527fb42f1f3f5388484ad/src/assets/scss/components/_table.scss#L1

**Comment by robertmarney** [comment]
Has anyone found a work-around for this?

**Comment by robertmarney** [comment]
`app.js`

```js
const customBulmaConfig = {
  ...bulmaConfig,
  table: {
    ...bulmaConfig.table,
    stickyHeaderClass: 'has-sticky-header',
  },
};

app.use(router).use(Oruga, customBulmaConfig).mount('#app');
```

**Comment by jtommy** [comment]
Can you make a PR?

**Comment by urkle** [comment]
@robertmarney do note (per my description) that even that configuration tweak does not fully work. As the filter row does not stick.
