### ISSUE TITLE
inputitems sizing does not work correctly.

### ISSUE THREAD

**Issue by urkle** [oruga-ui/theme-bulma#64]
When I set the size to small
```html
<o-inputitems size="small"/>
```

the component display small initially, however as soon as an entry is selected it increases in size.

The issues I've found so far are:

1. when blank the o-inputitems component renders at 30.7px high (vs a o-input control as small renders at 30px)
   - this causes visual discontinuity between the two components when next to each other (e.g. as filter on an o-table)
![image](https://user-images.githubusercontent.com/101123/182686050-d3f26cbc-e35b-4dfa-9ff8-268615256ad4.png)

2. when an entry is added to the o-inputitems the size increases to 36.1667px
![image](https://user-images.githubusercontent.com/101123/182686000-ee09c97d-ccab-4334-afaf-e1a79c65e32a.png)

Other sizes are also not inline either.
default 40 vs 39.8
medium 50 vs 48.9
large 60 vs 58

for Buefy the taginput sizes are  29.6, 39.8, 50, 60.2 and do not have the issue of changing sizes with or without the "tags".

**Comment by jtommy** [comment]
@urkle can you test with last version of Oruga 0.8.x and theme 0.3.x?

**Comment by mlmoravek** [comment]
This issue appears to have been resolved.
