### ISSUE TITLE
Notification renders double close button

### ISSUE THREAD

**Issue by groundfloorwebb** [oruga-ui/theme-bulma#65]
First off, great library, keep up the good work!

I'm using @oruga-ui/oruga-next 0.5.6 and @oruga-ui/theme-bulma 0.2.7 in a Vue 3 app with fontawesome. When I open a notification like this

```
	const { oruga } = useProgrammatic();
	oruga.notification.open({
		message: 'This is a test error message',
		variant: 'danger',
		closable: true,
	});
```
oruga creates a notification with a double close button like this

![Screen Shot 2022-09-16 at 12 39 03 PM](https://user-images.githubusercontent.com/71079085/190688150-c00e2f47-45d2-461f-83f0-8b4cf6b9332f.png)

This issue is theme applies bulma's `delete` class to the close element (creating the circular close button using css) and also generates an icon using the default value of the `closeIcon` prop in the component. I was able to get around this problem by passing an empty string for closeIcon in my config like this:

```
import oruga from '@oruga-ui/oruga-next';
import { bulmaConfig } from '@oruga-ui/theme-bulma';
import { merge } from 'lodash';

export const overrideConfig = {
	notification: {
		// This removes a duplicate close icon
		closeIcon: '',
	},
};

app.use(oruga, merge(bulmaConfig, overrideConfig));
```

I would recommend making this a part of the theme for a smoother dev experience.

**Comment by jtommy** [comment]
Can you open a PR to remove in the config file?

**Comment by groundfloorwebb** [comment]
@jtommy how's this? https://github.com/oruga-ui/theme-bulma/pull/66

**Comment by groundfloorwebb** [comment]
Also, looks like this is only an issue when using the FontAwesomeIcon component to render the icons.

**Comment by jtommy** [comment]
@groundfloorwebb I'm running the demo project and it looks ok without any changes...

![image](https://user-images.githubusercontent.com/8029488/190863463-d70ade1d-4368-45dd-a188-f7977f497d71.png)

Can you reproduce it on codepen or similar?

**Comment by groundfloorwebb** [comment]
Well looks like the real issue was i was including a snippet of buefy css leftover from the previous version of our design system. With that code removed the icon is still rendered but has a size of 0px, just like the example code. I feel silly, but the good news is this resolved another strange issue as well.
