### ISSUE TITLE
Please provide examples on how to use theme-bulma with Vue 2, especially when importing single components

### ISSUE THREAD

**Issue by kyle-jennings** [oruga-ui/theme-bulma#67]
the readme states: 'Please note, the package also works for @oruga-ui/oruga (Vue 2) and you can use it without importing the full Oruga bundle.' and while I am not using Vue 2, I am still using the Options API.  So I would import components like

```
import { OButton } from '@oruga-ui/oruga-next';
import { bulmaConfig } from '@oruga-ui/theme-bulma';

export default {
  components: {
    OButton
  }
  ...blah blah blah
}
```

But how would I use the `bulmaConfig` to configure that individual components where there are needed? I really do not want to import the entire package into my app, I only need a few components.

**Comment by jtommy** [comment]
https://vue2.oruga.io/documentation/#adding-classes, third example

**Comment by kyle-jennings** [comment]
@jtommy that did not help, that's documentation is for Vue 2.  I just edited my post to specify that  I am using Vue 3, but I am using the Options API.

So my main.js file has the createApp().mount() stuff from Vue 3, but my individual components are just importing other apps the standard way:
```
/// my-component.vue
import { OButton } from '@oruga-ui/oruga-next';
import { bulmaConfig } from '@oruga-ui/theme-bulma';

export default {
  components: {
    OButton
  }
  ...blah blah blah
}
```

So Vue.use() doesnt work here, if I try to import Vue from the vue package like so:

`import Vue from 'vue';`

I get this error in my terminal:
`export 'default' (imported as 'Vue') was not found in 'vue' (possible exports:` so my console would show:

`TypeError: Cannot read properties of undefined (reading 'use')`

All the documentation for the Vue3 examples have the Oruga components being imported into the main app, and not individual components like I am attempting to do.

Do we have to import Oruga components at the global (root) level instead of in individual components?

**Comment by jtommy** [comment]
https://oruga.io/documentation/#adding-classes, always third example

**Comment by kyle-jennings** [comment]
Ah ok I see, so I dont need to import the component globally (which is what the examples show) but I need to use the Config plugin globally and pass in the bulmaConfigs.
