### ISSUE TITLE
Modal ok/cancel button

### ISSUE THREAD

**Issue by danimog** [oruga-ui/theme-bulma#70]
In the example: https://oruga.io/components/modal.html
ModalForm import the _modal-form-async.vue file.
Where can I find the code of this file?

I don't know how return ok/cancel event.

Thanks a lot!

**Comment by jtommy** [comment]
https://github.com/oruga-ui/oruga/blob/develop/packages/docs-next/.vitepress/theme/examples/modal/_modal-form-async.vue
