### ISSUE TITLE
How to set mdi icons

### ISSUE THREAD

**Issue by danimog** [oruga-ui/theme-bulma#77]
Hello,
how can I add mdi icons in theme?
my main.js:
import '@oruga-ui/theme-bulma/dist/bulma.css'
import { bulmaConfig } from '@oruga-ui/theme-bulma'
createApp(App).use(Oruga, bulmaConfig).use(router).mount('#app')

Thanks!

**Comment by jtommy** [comment]
You have to import MDI icon pack

**Comment by danimog** [comment]
Thanks. Resolved.
1. yarn add @mdi/font
2. add in main.js:
import '@mdi/font/css/materialdesignicons.min.css';
