### ISSUE TITLE
Duplicated close icons

### ISSUE THREAD

**Issue by andrzejkupczyk** [oruga-ui/theme-bulma#80]
The problem affects `Modal`, `Inputitems` and probably other closable components (based on #65)

![image](https://user-images.githubusercontent.com/11018286/221815807-24e9bc99-077e-498a-9231-03d0009863e2.png)

Oruga, by default, uses "close" icon. Bulma, on the other hand, uses "delete" class. In the result both close icons appears:

```html
<span class="tag">
  <span>rock</span>
  <span class="icon is-clickable delete is-small"> <!-- delete class (bulma) -->
    <i class="mdi mdi-close mdi-24px"></i> <!-- close icon (oruga) -->
  </span>
</span>
```

Is there any way to fix this other than using empty close icon or template slot? Maybe it could be fixed within the theme itself?

```vue
<OInputitems close-icon="" />

<OInputitems>
  <slot #selected>
    <!-- customized template -->
  </slot>
</OInputitems>
```

**Comment by jtommy** [comment]
Yes, we should fix it by theme in order to use internal icon probably

**Comment by zhaolinlau** [comment]
any update?

**Comment by jtommy** [comment]
it should works with 0.3.0 and Oruga 0.8.x
