### ISSUE TITLE
Variable name not aligned with Oruga

### ISSUE THREAD

**Issue by alqu** [oruga-ui/theme-bulma#91]
I tried to adjust the height of an autocomplete using sass and was wondering why the variable `$autocomplete-menu-max-height` was not working.
After digging into the Bulma-theme, I stumbled upon this line:

https://github.com/oruga-ui/theme-bulma/blob/55dbaf43b87f01e31e003430c9963c94b93ab512/src/assets/scss/components/_autocomplete.scss#L2

I guess the variable needs to be renamed to `$autocomplete-menu-max-height` in line 2 and 16.

**Comment by jtommy** [comment]
Bulma theme uses its variable and they could be different from oruga base theme
