### ISSUE TITLE
Update of the theme for the new version 0.8

### ISSUE THREAD

**Issue by messenjer** [oruga-ui/theme-bulma#92]
Hello @jtommy @mlmoravek 

Thanks for the new release. 

Are there any plans for someone to update the theme-bulma with the new version 0.8 ?

Some properties need to be renamed in [the file bulma.ts](https://github.com/oruga-ui/theme-bulma/blob/master/src/plugins/bulma.ts), following the migration information in the [changelog v0.8] (https://github.com/oruga-ui/oruga/blob/develop/CHANGELOG.md)

```
rename elementsWrapperClass to wrapperClass class
...
```

https://oruga.io/components/Input.html

![Screenshot 2023-12-11 at 09 57 17](https://github.com/oruga-ui/theme-bulma/assets/80677/30697ec7-a02a-4d8a-8520-67bde3b263cd)

Regards

Mathieu

**Comment by jtommy** [comment]
We'll work to align the custom themes, the our priority was the new release itself.

Anyway any help is appreciated 👍

**Comment by jtommy** [comment]
@messenjer are you working on theme refactoring?

**Comment by messenjer** [comment]
Sorry, I didn't work on the refactoring. I was waiting for a new version with this fix https://github.com/oruga-ui/oruga/pull/687

**Comment by mlmoravek** [comment]
@messenjer The new version 0.8.2 with the fixed type definition should be out now. So you could start updating the theme if you like :)

**Comment by messenjer** [comment]
@jtommy I'm gearing up for the migration 0.7 to 0.8. Given my upcoming two-week vacation, I've kickstarted the process by linting and formatting the code to match the conventions used in other Oruga repositories.

This ensures that the upcoming Pull Request will focus solely on migration changes, making it easier to review.

https://github.com/oruga-ui/theme-bulma/pull/94

**Comment by messenjer** [comment]
I've renamed the Bulma theme class variables in line with the changelog notes (the PR is here: https://github.com/oruga-ui/theme-bulma/pull/95).

However, there are still some fixes needed in the theme's SCSS, and there's the potential use of teleport, but it's not really my expertise.

I'm off for a two-week vacation now. I'm hopeful that someone can pick up where I left off. Your expertise in handling SCSS would be greatly appreciated.

Thanks again for the evolution of the project; the library's typing is really helpful `OrugaOptions`.

**Comment by zhaolinlau** [comment]
any update?

**Comment by noebisoft** [comment]
I'm also eagerly awaiting the update. I think more people comming from Buefy feel the same way.

Is there an approximate time frame?

Is there a hack / workarround to fix this on the users side?

**Comment by jtommy** [comment]
@messenjer only to know, you are working on it?

**Comment by messenjer** [comment]
Sorry, for the CSS fixes, as I was explaining, it's not my area of expertise. I'm not working on it.

**Comment by AlexOstrovsky** [comment]
@jtommy @mlmoravek any plan on updating the theme to work with 0.8 version of oruga?

**Comment by jtommy** [comment]
The new release introduced breaking changes and other side effects, so there is more work to do to adapt the Bulma theme

**Comment by zhaolinlau** [comment]
any update?
