### ISSUE TITLE
Problems with mouse hovering for slider and dropdown component

### ISSUE THREAD

**Issue by major-mayer** [oruga-ui/theme-bulma#96]
Hi everybody,
Because Vue 2 is EOL now, I finally want to migrate some older projects from Vue 2 to Vue 3.
Because Buefy doesn't support Vue 3 I would like to migrate the UI toolkit to Orgua with the Bulma theme as well.

However, during my evaluation of the Orgua I noticed a lot of hover issue that seem to be present when using Firefox (119) and Chrome (120) (both on Linux).
I will show you a few screen recordings that I took from the website. 

The first one is regarding the Slider component, which my website uses quite a lot.
As you can see, as soon as you move the mouse over the thumb, the tooltip appears but flickers heavily.
This seems to be the case with both Bulma and Bootstrap theme.
[Screencast from 2024-01-08 15-38-39.webm](https://github.com/oruga-ui/theme-bulma/assets/17907799/27e04e62-28a1-4bd5-a00a-205a3314bd15)

The next issue I noticed is the dropdown component in hover mode when using smaller screen sizes.
As you can see, as soon as you move the mouse over the dropdown component, the menu opens (correct) but also the whole screen turns dark, because apparently an overlay is added.
[Screencast from 2024-01-08 15-47-33.webm](https://github.com/oruga-ui/theme-bulma/assets/17907799/eea54299-7f34-47ee-9ff0-834c44c0ec64)

Are those known issues?
And if yes, I would like to ask if this UI toolkit can be considered to be production ready or more of a work-in-progress project?

Edit: In both cases, the base Orgua style seems to be unaffected.

**Comment by whiplashwebb** [comment]
@major-mayer i ran into this while updating the Bulma theme and it should be resolved once this merges. I haven't checked the bootstrap theme but i think it would fix it there too.
